# Generated by Django 3.1.7 on 2021-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210415_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='unread',
            field=models.BooleanField(default=False),
        ),
    ]
