# Generated by Django 3.1.7 on 2021-04-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
